src/Entity/Order.php
<?php

namespace App\Entity;

use App\Entity\OrderDetail;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\OrderRepository;
use App\Entity\Trait\CreatedAtTrait;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    use CreatedAtTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $reference = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?UserAdress $deliveryAdress = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?UserAdress $billingAdress = null;

    #[ORM\Column]
    private ?int $Amount = null;

    #[ORM\Column]
    private ?bool $paid = null;

    #[ORM\OneToMany(mappedBy: 'orderid', targetEntity: OrderDetail::class, orphanRemoval: true)]
    private Collection $orderDetails;


    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetail $orderDetail): self
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails->add($orderDetail);
            $orderDetail->setOrderid($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetail $orderDetail): self
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            $orderDetail->setOrderid(null);
        }

        return $this;
    }

    public function getDeliveryAdress(): ?UserAdress
    {
        return $this->deliveryAdress;
    }

    public function setDeliveryAdress(?UserAdress $deliveryAdress): self
    {
        $this->deliveryAdress = $deliveryAdress;

        return $this;
    }

    public function getBillingAdress(): ?UserAdress
    {
        return $this->billingAdress;
    }

    public function setBillingAdress(?UserAdress $billingAdress): self
    {
        $this->billingAdress = $billingAdress;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->Amount;
    }

    public function setAmount(int $Amount): self
    {
        $this->Amount = $Amount;

        return $this;
    }

    public function isPaid(): ?bool
    {
        return $this->paid;
    }

    public function setPaid(bool $paid): self
    {
        $this->paid = $paid;

        return $this;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\UserAdress;
use App\Form\UserPasswordType;
use App\Form\UserType;
use App\Service\UserAdressService;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

#[Route('/profile', name: 'profile')]
class ProfileController extends AbstractController
{
    #[Route('/', name: '_index')]
    public function index(): Response
    {
        return $this->render('profile/index.html.twig');
    }

    #[Route('/adresse/add', name: '_adress_add')]
    public function addAdress(UserAdressService $userService): Response
    {
        $adressForm = $userService->add();

        return $this->render('profile/addAdress.html.twig', [
            'adressForm' => $adressForm->createView(),
        ]);
    }

    #[Route('/adresse/edit/{id}', name: '_adress_edit')]
    public function editAdress(UserAdressService $userService, UserAdress $userAdress): Response
    {
        $adressForm = $userService->edit($userAdress);

        return $this->render('profile/editAdress.html.twig', [
            'adressForm' => $adressForm->createView(),
        ]);
    }

    #[Route('/adresse/delete/{id}', name: '_adress_delete')]
    public function deleteAdress(UserAdressService $userService, UserAdress $userAdress): Response
    {
        $userService->delete($userAdress);

        return $this->redirectToRoute('profile_index');
    }

    #[Route('/modifier-informations', name: '_user_edit')]
    public function editInfos(Request $request, ManagerRegistry $managerRegistry): Response
    {
        $user = $this->getUser();
        $userForm = $this->createForm(UserType::class, $user);
        $userForm->handleRequest($request);

        if ($userForm->isSubmitted() && $userForm->isValid()) {
            $manager = $managerRegistry->getManager();
            $user = $userForm->getData();
            $manager->persist($user);
            $manager->flush();
            return $this->redirectToRoute('profile_index');
        }
        return $this->render('profile/editUser.html.twig', [
            'userForm' => $userForm->createView(),
        ]);
    }

    #[Route('/modifier-mdp/{id}', name: '_password_edit')]
    public function editPassword(User $user, Request $request, ManagerRegistry $managerRegistry, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        $passwordForm = $this->createForm(UserPasswordType::class);
        $passwordForm->handleRequest($request);

        if ($passwordForm->isSubmitted() && $passwordForm->isValid()) {
            if ($userPasswordHasher->isPasswordValid($user, $passwordForm->get('plainPassword')->getData())) {
                $manager = $managerRegistry->getManager();
                $user->setPassword(
                    $userPasswordHasher->hashPassword(
                        $user,
                        $passwordForm->get('newPassword')->getData()
                    )
                );
                $manager->flush();
                $this->addFlash('success', 'Votre mot de passe a bien été modifié');
                return $this->redirectToRoute('profile_index');
            } else {
                $this->addFlash('error', 'Votre ancien mot de passe n\'est pas le bon');
            }
        }

        return $this->render('profile/editPassword.html.twig', [
            'passwordForm' => $passwordForm->createView(),
        ]);
    }
}

templates/profile/addAdress.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une adresse{% endblock %}

{% block stylesheets %}
<!-- product CSS -->
<link rel="stylesheet" href="{{ asset('assets/css/contact.css') }}">
{% endblock %}

{% block body %}

<article>
    <div class="container">
        <h1>Ajouter une adresse</h1>
        {{ form_start(adressForm) }}
        {{ form_row(adressForm.adressline) }}
        {{ form_row(adressForm.city) }}
        {{ form_row(adressForm.zipcode) }}
        {{ form_row(adressForm.phone) }}
        <button class="btn btn-dark" type="submit" class="btn btn-secondary">Valider</button>
        {{ form_end(adressForm) }}
    </div>
</article>

{% endblock %}

templates/profile/editAdress.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une adresse{% endblock %}

{% block stylesheets %}
<!-- product CSS -->
<link rel="stylesheet" href="{{ asset('assets/css/contact.css') }}">
{% endblock %}

{% block body %}

<article>
    <div class="container">
        <h1>Modifier une adresse</h1>
        {{ form_start(adressForm) }}
        {{ form_row(adressForm.adressline) }}
        {{ form_row(adressForm.city) }}
        {{ form_row(adressForm.zipcode) }}
        {{ form_row(adressForm.phone) }}
        <button class="btn btn-dark" type="submit" class="btn btn-secondary">Valider</button>
        {{ form_end(adressForm) }}
    </div>
</article>

{% endblock %}

templates/profile/editPassword.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier mon mot de passe{% endblock %}

{% block stylesheets %}
<!-- product CSS -->
<link rel="stylesheet" href="{{ asset('assets/css/contact.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/editUser.css') }}">
{% endblock %}

{% block body %}

<article>
    <div class="container">
        <h1>Modifier mon mot de passe</h1>
        {{ form_start(passwordForm) }}
        {{ form_row(passwordForm.plainPassword) }}
        <div class="form-row">
            {{ form_row(passwordForm.newPassword.first) }}
            {{ form_row(passwordForm.newPassword.second) }}
        </div>
        <button class="btn btn-dark" type="submit" class="btn btn-secondary">Valider</button>
        {{ form_end(passwordForm) }}
    </div>
</article>

{% endblock %}

templates/profile/editUser.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier mes informations{% endblock %}

{% block stylesheets %}
<!-- product CSS -->
<link rel="stylesheet" href="{{ asset('assets/css/contact.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/editUser.css') }}">
{% endblock %}

{% block body %}

<article>
    <div class="container">
        <h1>Modifier mes informations</h1>
        {{ form_start(userForm) }}
        <div class="form-row">
            {{ form_row(userForm.firstname) }}
            {{ form_row(userForm.lastname) }}
        </div>
        {{ form_row(userForm.email) }}
        <button class="btn btn-dark" type="submit">Valider</button>
        {{ form_end(userForm) }}
    </div>
</article>

{% endblock %}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon compte{% endblock %}

{% block stylesheets %}
<!-- profile CSS -->
<link rel="stylesheet" href="{{ asset('assets/css/profile.css') }}">
{% endblock %}

{% block javascripts %}
<script src="{{ asset('assets/js/profile.js') }}"></script>
{% endblock %}

{% block body %}

<section>
    <div class="container">
        <h1>Mon compte</h1>
        <div class="account">
            <div class="order-section">
                <h2>Commandes</h2>
                <div class="orders">
                    {% for order in app.user.orders %}
                    <div class="order">
                        <a class="details">
                            <p><span id="date">Date</span> : {{ order.createdAt|date('Y-m-d') }} ({{ (order.amount / 100)|number_format('2', ',', ' ') }} €)</p>
                            <i class="fa-solid fa-chevron-down open-icon"></i>
                        </a>
                        <div class="order-detail">
                            <p class="ref">Référence : {{ order.reference }} </p>
                            {% for orderDetail in order.orderDetails %}
                            <div class="product">
                                <a href="{{ path('products_product', {slug: orderDetail.product.slug}) }}">
                                    <img src="/assets/img/product/mainImg/{{ orderDetail.product.mainImage }}"
                                        alt="Photo d'un produits de la commande">
                                </a>
                                <div class="product-details">
                                    <div class="product-info">
                                        <p>{{ orderDetail.product.name}}</p>
                                        <p class="mt">{{ (orderDetail.product.price / 100)|number_format('2', ',', ' ') }} €</p>
                                    </div>
                                    <div class="product-quantity">
                                        <p>Quantité</p>
                                        <p class="mt">{{ orderDetail.quantity}}</p>
                                    </div>
                                    <div class="product-total">
                                        <p>Total</p>
                                        <p class="mt">{{ ((orderDetail.quantity * orderDetail.product.price) /100)|number_format('2', ',', ' ') }} €</p>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="infos">
                <div class="title">
                    <h2>Mes adresses</h2>
                    <a href="{{ path('profile_adress_add') }}" class="add">Ajouter une adresse</a>
                </div>
                <div class="adresses">
                    {% for address in app.user.userAdresses %}
                    <div class="adress">
                        <p>{{ address.adressLine }}</p>
                        <p>{{ address.zipcode }}</p>
                        <p>{{ address.city }}</p>
                        <p>{{ address.phone }}</p>
                        <div class="adress-crud">
                            <a href="{{ path('profile_adress_edit', {id: address.id}) }}">Modifier</a>
                            <a href="{{ path('profile_adress_delete', {id: address.id}) }}" class="delete">Supprimer</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="info-section">
                    <div class="title">
                        <h2>Mes informations</h2>
                        <a href="{{ path('profile_user_edit') }}" class="add">Modifier mes informations</a>
                    </div>
                    <div class="info-detail">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <th>Nom</th>
                                    <td>{{ app.user.lastname }}</td>
                                </tr>
                                <tr>
                                    <th>Prénom</th>
                                    <td>{{ app.user.firstname }}</td>
                                </tr>
                                <tr>
                                    <th>Email</th>
                                    <td>{{ app.user.email }}</td>
                                </tr>
                            </tbody>
                        </table>
                        <a href="{{ path('profile_password_edit', {id: app.user.id}) }}" class="edit-password">Modifier
                            mon mot de passe</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}